# Generated by Django 3.1.4 on 2020-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='age',
            field=models.SmallIntegerField(default=25),
            preserve_default=False,
        ),
    ]
