# Generated by Django 3.1.2 on 2020-12-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_healthcheck_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
